const GTM='GTM-KTCT795B';
function push(event,extra={}){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event,...extra})}
function loadGTM(){if(window.__gtmLoaded)return;window.__gtmLoaded=true;const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtm.js?id='+GTM;document.head.appendChild(s)}
loadGTM();
const consent=localStorage.getItem('ip_consent');const cookie=document.getElementById('cookie');if(!consent){cookie.classList.add('show')}else{const granted=consent==='accepted'?'granted':'denied';gtag('consent','update',{ad_storage:granted,analytics_storage:granted,ad_user_data:granted,ad_personalization:granted})}
function setConsent(v){localStorage.setItem('ip_consent',v);gtag('consent','update',{ad_storage:v==='accepted'?'granted':'denied',analytics_storage:v==='accepted'?'granted':'denied',ad_user_data:v==='accepted'?'granted':'denied',ad_personalization:v==='accepted'?'granted':'denied'});push('ip_consent_update',{consent_choice:v});cookie.classList.remove('show')}
document.getElementById('accept').onclick=()=>setConsent('accepted');document.getElementById('essential').onclick=()=>setConsent('rejected');
const p=new URLSearchParams(location.search);const variant=['telhados','terracos'].includes(p.get('servico'))?p.get('servico'):'geral';
const variants={geral:{ey:'IMPERMEABILIZAÇÃO PROFISSIONAL',title:'Impermeabilização de telhados, terraços e coberturas',body:'Nova impermeabilização, renovação e reparação com tela asfáltica, para prevenir problemas ou resolver infiltrações existentes.'},telhados:{ey:'TELHADOS E COBERTURAS',title:'Impermeabilização de telhados e coberturas',body:'Nova impermeabilização, renovação e reparação de coberturas para prevenir entrada de água ou resolver problemas existentes.'},terracos:{ey:'TERRAÇOS E VARANDAS',title:'Impermeabilização de terraços e varandas',body:'Nova impermeabilização, renovação e reparação para proteger o terraço contra água e humidade ou resolver infiltrações existentes.'}};
document.getElementById('heroEyebrow').textContent=variants[variant].ey;document.getElementById('heroTitle').textContent=variants[variant].title;document.getElementById('heroBody').textContent=variants[variant].body;
const directMsg=variant==='telhados'?'Olá. Gostaria de pedir uma avaliação para impermeabilização de um telhado/cobertura.':variant==='terracos'?'Olá. Gostaria de pedir uma avaliação para impermeabilização de um terraço/varanda.':'Olá. Gostaria de pedir uma avaliação para um trabalho de impermeabilização.';
document.querySelectorAll('.wa-direct').forEach(a=>a.href='https://wa.me/351930446198?text='+encodeURIComponent(directMsg));
const state={tipo:variant==='telhados'?'Telhado / cobertura':variant==='terracos'?'Terraço / varanda':'',situacao:'',area:''};
document.querySelectorAll('.choice-grid').forEach(group=>{const name=group.dataset.name;group.querySelectorAll('button').forEach(btn=>{if(btn.dataset.value===state[name])btn.classList.add('active');btn.addEventListener('click',()=>{state[name]=btn.dataset.value;group.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn))})})});
document.getElementById('quickForm').addEventListener('submit',e=>{e.preventDefault();const locality=document.getElementById('localidade').value.trim()||'Por indicar';const type=state.tipo||'Por definir',sit=state.situacao||'Por explicar',area=state.area||'Por indicar';const msg=['Olá. Gostaria de pedir uma avaliação para um trabalho de impermeabilização.',`Zona: ${type}`,`Situação: ${sit}`,`Área aproximada: ${area}`,`Localidade: ${locality}`,'Posso enviar fotografias ou vídeo se ajudar na avaliação.'].join('\n');push('ip_quick_request',{landing_variant:variant,request_type:type,request_situation:sit,request_area:area,page_path:location.pathname+location.search});push('ip_contact_click',{contact_action:'whatsapp_quick_request',landing_variant:variant});window.open('https://wa.me/351930446198?text='+encodeURIComponent(msg),'_blank','noopener,noreferrer')});
document.querySelectorAll('[data-track]').forEach(a=>a.addEventListener('click',()=>push('ip_phone_click',{placement:a.dataset.track,landing_variant:variant,page_path:location.pathname+location.search})));
document.querySelectorAll('.wa-direct').forEach(a=>a.addEventListener('click',()=>push('ip_whatsapp_click',{placement:'direct',landing_variant:variant,page_path:location.pathname+location.search})));
